//
//  Language.swift
//  Good Travel
//
//  Created by Adam Mokhtar on 09/02/2021.
//

import Foundation
let languageList:[(name: String, value: String)] = [
  ("Afrikaans" , "af"),
  ("Albanais" , "sq"),
  ("Amharique" , "am"),
  ("Arabe" , "ar"),
  ("Arménien" , "hy"),
  ("Azéri" , "az"),
  ("Basque" , "eu"),
  ("Biélorusse" , "be"),
  ("Bengali" , "bn"),
  ("Bosnien" , "bs"),
  ("Bulgare" , "bg"),
  ("Catalan" , "ca"),
  ("Cebuano" , "ceb"),
  ("Chinois (simplifié)" , "zh-CN"),
  ("Chinois (traditionnel)" , "zh-TW"),
  ("Corse" , "co"),
  ("Croate" , "hr"),
  ("Tchèque" , "cs"),
  ("Danois" , "da"),
  ("Néerlandais" , "nl"),
  ("Anglais" , "en"),
  ("Espéranto" , "eo"),
  ("Estonien" , "et"),
  ("Finnois" , "fi"),
  ("Français" , "fr"),
  ("Frison" , "fy"),
  ("Galicien" , "gl"),
  ("Géorgien" , "ka"),
  ("Allemand" , "de"),
  ("Grec" , "el"),
  ("Gujarati" , "gu"),
  ("Créole haïtien" , "ht"),
  ("Haoussa" , "ha"),
  ("Hawaïen" , "haw"),
  ("Hébreu" , "he"),
  ("Hindi" , "hi"),
  ("Hmong" , "hmn"),
  ("Hongrois" , "hu"),
  ("Islandais" , "is"),
  ("Igbo" , "ig"),
  ("Indonésien" , "id"),
  ("Irlandais" , "ga"),
  ("Italien" , "it"),
  ("Japonais" , "ja"),
  ("Javanais" , "jv"),
  ("Kannada" , "kn"),
  ("Kazakh" , "kk"),
  ("Khmer" , "km"),
  ("Kinyarwanda" , "rw"),
  ("Coréen" , "ko"),
  ("Kurde" , "ku"),
  ("Kirghyz" , "ky"),
  ("Laotien" , "lo"),
  ("Latin" , "la"),
  ("Letton" , "lv"),
  ("Lituanien" , "lt"),
  ("Luxembourgeois" , "lb"),
  ("Macédonien" , "mk"),
  ("Malgache" , "mg"),
  ("Malais" , "ms"),
  ("Malayâlam" , "ml"),
  ("Maltais" , "mt"),
  ("Maori" , "mi"),
  ("Marathi" , "mr"),
  ("Mongol" , "mn"),
  ("Birman" , "my"),
  ("Népalais" , "ne"),
  ("Norvégien" , "no"),
  ("Nyanja (Chichewa)" , "ny"),
  ("Odia (Oriya)" , "or"),
  ("Pachtô" , "ps"),
  ("Perse" , "fa"),
  ("Polonais" , "pl"),
  ("Portugais (Portugal, Brésil)" , "pt"),
  ("Panjabi" , "pa"),
  ("Roumain" , "ro"),
  ("Russe" , "ru"),
  ("Samoan" , "sm"),
  ("Gaélique (Écosse)" , "gd"),
  ("Serbe" , "sr"),
  ("Sesotho" , "st"),
  ("Shona" , "sn"),
  ("Sindhî" , "sd"),
  ("Singhalais" , "si"),
  ("Slovaque" , "sk"),
  ("Slovène" , "sl"),
  ("Somali" , "so"),
  ("Spanish" , "es"),
  ("Soundanais" , "su"),
  ("Swahili" , "sw"),
  ("Suédois" , "sv"),
  ("Tagalog (philippin)" , "tl"),
  ("Tadjik" , "tg"),
  ("Tamoul" , "ta"),
  ("Tatar" , "tt"),
  ("Télougou" , "te"),
  ("Thaï" , "th"),
  ("Turc" , "tr"),
  ("Turkmène" , "tk"),
  ("Ukrainien" , "uk"),
  ("Urdu" , "ur"),
  ("Ouïghour" , "ug"),
  ("Ouzbek" , "uz"),
  ("Vietnamien" , "vi"),
  ("Gallois" , "cy"),
  ("Xhosa" , "xh"),
  ("Yiddish" , "yi"),
  ("Yoruba" , "yo"),
  ("Zulu" , "zu")
]
